In [1]:
print("Lets Get This Party Started")
import os
import pickle
import cv2
import glob
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

Lets Get This Party Started


In [2]:
# Prepare Object Points: Points referenced to actual object in distorted image
# Object Points: 3D points in real world space
# Image Points: 2D points in image plane
# Calibration setup
nx = 9 #Calibration Images: Number of inside corners in x
ny = 5 #Calibration Images: Number of inside corners in y

# Define "Standard Object Points"
points_obj_std = np.zeros((nx*ny,3),np.float32)
points_obj_std[:,:2] = np.mgrid[0:nx,0:ny].T.reshape(-1,2) 
print('points_obj_std',points_obj_std)

# Create empty arrays
points_object = []
points_image = []

#Create list of calibration images
images_calibration = glob.glob('../camera_cal/calibration1.jpg')
print('images_calibration',images_calibration)

# Loop through calibration image list and extract chessboard corner data
for idx, fname in enumerate(images_calibration):
    # Read in image
    img = cv2.imread(fname)
    # Convert to grayscale
    img_grey = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    # Find chessboard corners
    ret, corners = cv2.findChessboardCorners(img_gray, (nx, ny), None)
    #print('findChessboardCorners',ret,corners)
    
    # Record corners if found
    if ret == True:
        # Append Object Points (standard array) and Image Points (extracted corners)
        points_object.append(points_obj_std)
        points_image.append(corners)
        # Display Corners
        #cv2.drawChessboardCorners(img, (nx, ny), corners, ret)
        #write_name = 'corners_found'+str(idx)+'.jpg'
        #cv2.imwrite(write_name, img)
        #cv2.imshow('img', img)
        #cv2.waitKey(500)
print('Completed')


points_obj_std [[0. 0. 0.]
 [1. 0. 0.]
 [2. 0. 0.]
 [3. 0. 0.]
 [4. 0. 0.]
 [5. 0. 0.]
 [6. 0. 0.]
 [7. 0. 0.]
 [8. 0. 0.]
 [0. 1. 0.]
 [1. 1. 0.]
 [2. 1. 0.]
 [3. 1. 0.]
 [4. 1. 0.]
 [5. 1. 0.]
 [6. 1. 0.]
 [7. 1. 0.]
 [8. 1. 0.]
 [0. 2. 0.]
 [1. 2. 0.]
 [2. 2. 0.]
 [3. 2. 0.]
 [4. 2. 0.]
 [5. 2. 0.]
 [6. 2. 0.]
 [7. 2. 0.]
 [8. 2. 0.]
 [0. 3. 0.]
 [1. 3. 0.]
 [2. 3. 0.]
 [3. 3. 0.]
 [4. 3. 0.]
 [5. 3. 0.]
 [6. 3. 0.]
 [7. 3. 0.]
 [8. 3. 0.]
 [0. 4. 0.]
 [1. 4. 0.]
 [2. 4. 0.]
 [3. 4. 0.]
 [4. 4. 0.]
 [5. 4. 0.]
 [6. 4. 0.]
 [7. 4. 0.]
 [8. 4. 0.]]
images_calibration ['../camera_cal/calibration1.jpg']


NameError: name 'img_gray' is not defined

In [3]:
# Prepare Object Points: Points referenced to actual object in distorted image
# Object Points: 3D points in real world space
# Image Points: 2D points in image plane
# Calibration setup
nx = 9 #Calibration Images: Number of inside corners in x
ny = 5 #Calibration Images: Number of inside corners in y

# Define "Standard Object Points"
points_obj_std = np.zeros((nx*ny,3),np.float32)
points_obj_std[:,:2] = np.mgrid[0:nx,0:ny].T.reshape(-1,2) 
print('points_obj_std',points_obj_std)

# Create empty arrays
points_object = []
points_image = []

#Create list of calibration images
images_calibration = glob.glob('../camera_cal/calibration1.jpg')
print('images_calibration',images_calibration)

# Loop through calibration image list and extract chessboard corner data
for idx, fname in enumerate(images_calibration):
    # Read in image
    img = cv2.imread(fname)
    # Convert to grayscale
    img_gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    # Find chessboard corners
    ret, corners = cv2.findChessboardCorners(img_gray, (nx, ny), None)
    #print('findChessboardCorners',ret,corners)
    
    # Record corners if found
    if ret == True:
        # Append Object Points (standard array) and Image Points (extracted corners)
        points_object.append(points_obj_std)
        points_image.append(corners)
        # Display Corners
        #cv2.drawChessboardCorners(img, (nx, ny), corners, ret)
        #write_name = 'corners_found'+str(idx)+'.jpg'
        #cv2.imwrite(write_name, img)
        #cv2.imshow('img', img)
        #cv2.waitKey(500)
print('Completed')


points_obj_std [[0. 0. 0.]
 [1. 0. 0.]
 [2. 0. 0.]
 [3. 0. 0.]
 [4. 0. 0.]
 [5. 0. 0.]
 [6. 0. 0.]
 [7. 0. 0.]
 [8. 0. 0.]
 [0. 1. 0.]
 [1. 1. 0.]
 [2. 1. 0.]
 [3. 1. 0.]
 [4. 1. 0.]
 [5. 1. 0.]
 [6. 1. 0.]
 [7. 1. 0.]
 [8. 1. 0.]
 [0. 2. 0.]
 [1. 2. 0.]
 [2. 2. 0.]
 [3. 2. 0.]
 [4. 2. 0.]
 [5. 2. 0.]
 [6. 2. 0.]
 [7. 2. 0.]
 [8. 2. 0.]
 [0. 3. 0.]
 [1. 3. 0.]
 [2. 3. 0.]
 [3. 3. 0.]
 [4. 3. 0.]
 [5. 3. 0.]
 [6. 3. 0.]
 [7. 3. 0.]
 [8. 3. 0.]
 [0. 4. 0.]
 [1. 4. 0.]
 [2. 4. 0.]
 [3. 4. 0.]
 [4. 4. 0.]
 [5. 4. 0.]
 [6. 4. 0.]
 [7. 4. 0.]
 [8. 4. 0.]]
images_calibration ['../camera_cal/calibration1.jpg']
Completed


In [4]:
# Prepare Object Points: Points referenced to actual object in distorted image
# Object Points: 3D points in real world space
# Image Points: 2D points in image plane
# Calibration setup
nx = 9 #Calibration Images: Number of inside corners in x
ny = 5 #Calibration Images: Number of inside corners in y

# Define "Standard Object Points"
points_obj_std = np.zeros((nx*ny,3),np.float32)
points_obj_std[:,:2] = np.mgrid[0:nx,0:ny].T.reshape(-1,2) 
print('points_obj_std',points_obj_std)

# Create empty arrays
points_object = []
points_image = []

#Create list of calibration images
images_calibration = glob.glob('../camera_cal/calibration*.jpg')
print('images_calibration',images_calibration)

# Loop through calibration image list and extract chessboard corner data
for idx, fname in enumerate(images_calibration):
    # Read in image
    img = cv2.imread(fname)
    # Convert to grayscale
    img_gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    # Find chessboard corners
    ret, corners = cv2.findChessboardCorners(img_gray, (nx, ny), None)
    #print('findChessboardCorners',ret,corners)
    
    # Record corners if found
    if ret == True:
        # Append Object Points (standard array) and Image Points (extracted corners)
        points_object.append(points_obj_std)
        points_image.append(corners)
        # Display Corners
        #cv2.drawChessboardCorners(img, (nx, ny), corners, ret)
        #write_name = 'corners_found'+str(idx)+'.jpg'
        #cv2.imwrite(write_name, img)
        #cv2.imshow('img', img)
        #cv2.waitKey(500)
print('Completed')


points_obj_std [[0. 0. 0.]
 [1. 0. 0.]
 [2. 0. 0.]
 [3. 0. 0.]
 [4. 0. 0.]
 [5. 0. 0.]
 [6. 0. 0.]
 [7. 0. 0.]
 [8. 0. 0.]
 [0. 1. 0.]
 [1. 1. 0.]
 [2. 1. 0.]
 [3. 1. 0.]
 [4. 1. 0.]
 [5. 1. 0.]
 [6. 1. 0.]
 [7. 1. 0.]
 [8. 1. 0.]
 [0. 2. 0.]
 [1. 2. 0.]
 [2. 2. 0.]
 [3. 2. 0.]
 [4. 2. 0.]
 [5. 2. 0.]
 [6. 2. 0.]
 [7. 2. 0.]
 [8. 2. 0.]
 [0. 3. 0.]
 [1. 3. 0.]
 [2. 3. 0.]
 [3. 3. 0.]
 [4. 3. 0.]
 [5. 3. 0.]
 [6. 3. 0.]
 [7. 3. 0.]
 [8. 3. 0.]
 [0. 4. 0.]
 [1. 4. 0.]
 [2. 4. 0.]
 [3. 4. 0.]
 [4. 4. 0.]
 [5. 4. 0.]
 [6. 4. 0.]
 [7. 4. 0.]
 [8. 4. 0.]]
images_calibration ['../camera_cal\\calibration1.jpg', '../camera_cal\\calibration10.jpg', '../camera_cal\\calibration11.jpg', '../camera_cal\\calibration12.jpg', '../camera_cal\\calibration13.jpg', '../camera_cal\\calibration14.jpg', '../camera_cal\\calibration15.jpg', '../camera_cal\\calibration16.jpg', '../camera_cal\\calibration17.jpg', '../camera_cal\\calibration18.jpg', '../camera_cal\\calibration19.jpg', '../camera_cal\\calibration2.